//students array
let students = [
    {
        name: "ahmad",
        username: "admin",
        passward: "admin",
        gender: "male",
        marks: [78, 67, 45, 89, 70],
        role: "admin",
    },
    {
        name: "abuzar",
        username: "user",
        passward: "11111",
        gender: "male",
        marks: [58, 77, 85, 29, 30],
        role: "user",
    },
    {
        name: "ashfaq",
        username: "user",
        passward: "22222",
        gender: "male",
        marks: [58, 67, 85, 89, 76],
        role: "user",
    },
    {
        name: "abubakar",
        username: "user",
        passward: "33333",
        gender: "male",
        marks: [98, 97, 45, 69, 30],
        role: "user",
    },
    {
        name: "kainat",
        username: "user",
        passward: "44444",
        gender: "female",
        marks: [38, 47, 45, 39, 20],
        role: "user",
    },
    {
        name: "tamanaa",
        username: "user",
        passward: "55555",
        gender: "female",
        marks: [78, 87, 75, 89, 90],
        role: "user",
    },
    {
        name: "rukai",
        username: "user",
        passward: "66666",
        gender: "female",
        marks: [58, 47, 35, 39, 40],
        role: "user",
    },
    {
        name: "zafar",
        username: "user",
        passward: "88888",
        gender: "male",
        marks: [98, 67, 75, 99, 90],
        role: "user",
    },
    {
        name: "javerya",
        username: "user",
        passward: "99999",
        gender: "female",
        marks: [98, 87, 55, 99, 90],
        role: "user",
    },
    {
        name: "ihtisham",
        username: "user",
        passward: "10101",
        gender: "male",
        marks: [28, 27, 45, 16, 50],
        role: "user",
    },
];